
//
//  ExceptionPractice.cpp
//  ExceptionPractice
//

#include <iostream>
#include <exception>
using namespace std;

int main() {

	int num1 = 0;
	int num2 = 0;
	int result = 0;
	int errorCode = 1;

	try {
		cout << "Enter a number: ";
		cin >> num1;
		cout << "Enter a second number: ";
		cin >> num2;
		
		if(num1 == 0 || num2 == 0) {
			throw errorCode;
			}
		else {
			result = num2 / num1;
			}
		
		cout << "The result is: " << result << endl;
	}
	
	catch(int e)
	{
		cerr << "Cannot divide by 0. Error number: " << e << endl;
	}
	
	cin.get();
	cin.ignore();
}


