//
//  main.cpp
//  ExceptionPractice
//
//  Created by Jonathan Kinney on 4/27/16.
//  Copyright Â© 2016 Jonathan Kinney. All rights reserved.
//

#include <iostream>
#include <exception>
#include <string>
using namespace std;

int main() {

	int num1 = 0;
	int num2 = 0;
	int num = 0;
	string errorMessage = "Break thignS HAPEPEN SOMETIME!!!!!";
	string clocks = "Pls help";

	
	try {
		cout << "Enter a number: ";
		cin >> num;
		cout << "Enter a second number!!!! Yaye!!!: ";
		cin >> num2;
		
		if(num == 0 || num2 == 0)
			throw errorMessage;
		
		num1 = num2 / num;
		
		cout << "Resykt usj : " << num1 << endl;
		throw errorMessage;
	}
	
	catch(string e)
	{
		cerr << e << endl;
	}
	
	cin.get();
	cin.ignore();
}


